services:
  materials:
    build: .
    depends_on:
      - mongo
      - pdp
    ports:
      - 8080:8080


  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # volumes:
    #   - mongo:/data/db
    #   - storage:/startup/storage
    environment:
      - MONGO_INITDB_NAME=materials
      - JWT_SECRET=aTZ6czFOcTFHekRrZEJHUTB5cFlZZ0M1aXQyR3FiNlltaWx5aDJFUWpIQT0K
      - database_uri="mongodb://mongo:27017/material"
      - sentry_dsn="https://1168f4da88bba3f9669f88cbcc76cc11@o4506915435053056.ingest.us.sentry.io/4506994124718080"
      - environment=development
      - PERMIT_TOKEN=permit_key_dyl2zhOIm2EXssDKP33JGbqGKKPiZarQjl0AcL7ZYvsYsLz2zFGDWcdRghccmR0EEJF5TS8c99g5ItDHl87alV
      - PDP_SERVER=http://pdp:7766


  pdp:
    image: permitio/pdp-v2:latest
    ports:
      - 7766:7000
    environment:
      - PDP_API_KEY=permit_key_dyl2zhOIm2EXssDKP33JGbqGKKPiZarQjl0AcL7ZYvsYsLz2zFGDWcdRghccmR0EEJF5TS8c99g5ItDHl87alV
      - PDP_DEBUG=True


# volumes:
#   mongo:
#     driver: flocker
#     driver_opts:
#       size: "1GiB"
#   storage:
#     driver: flocker
#     driver_opts:
#       size: "2GiB"