database:
  kind: mongodb
  uri: mongodb+srv://madaurus:esisba@22@madaurus.nredljo.mongodb.net/materials?retryWrites=true&w=majority&appName=madaurus
  name: materials
  user: madaurus
  password: esisba@22
  host: madaurus.nredljo.mongodb.net

development:
  port: 8085
  host: localhost
  env: development

test:
  port: 8085
  host: localhost
  env: test
