name: Testing  Material Service Go (Gin)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
    ACR_RESOURCE_GROUP: madaurus
    AZURE_CONTAINER_REGISTRY: madaurus
    CONTAINER_NAME: materials
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      - name: Download Dependencies
        run : go mod download
      - name: Test
        run: go test -v ./test/unit/...
  build:
        runs-on: ubuntu-latest
       # needs:
       #   - test
        steps:
            - name: Login To Azure ACR
              run: docker login  madaurus.azurecr.io -u madaurus -p ${{secrets.AZURE_ACR}} 
            - name: Build and push image to ACR
              run: docker build -t  madaurus.azurecr.io/${{ env.CONTAINER_NAME }}:latest .
            - name: Push the Image
              run: docker pull madaurus.azurecr.io/${{ env.CONTAINER_NAME }}:latest
